---
fixtures:
    repositories:
        stdlib:
          ref: "4.12.0"
          repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
        hiera:
          ref: "2.0.1"
          repo: "https://github.com/voxpupuli/puppet-hiera"
        inifile:
          ref: "1.5.0"
          repo: "https://github.com/puppetlabs/puppetlabs-inifile"
        r10k:
          ref: "v3.2.0"
          repo: "https://github.com/acidprime/r10k"
        puppetdb:
          ref: "5.1.2"
          repo: "http://github.com/puppetlabs/puppetlabs-puppetdb"
        firewall:
          ref: "1.8.1"
          repo: "https://github.com/puppetlabs/puppetlabs-firewall"
        postgresql:
          ref: "4.8.0"
          repo: "https://github.com/puppetlabs/puppetlabs-postgresql"
        gcc:
          ref: "0.3.0"
          repo: "https://github.com/puppetlabs/puppetlabs-gcc"
        git:
          ref: "0.5.0"
          repo: "https://github.com/puppetlabs/puppetlabs-git"
        vcsrepo:
          ref: "1.3.2"
          repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
        pe_gem:
          ref: "0.1.2"
          repo: "https://github.com/puppetlabs/puppetlabs-pe_gem"
        ruby:
          ref: "0.5.0"
          repo: "https://github.com/puppetlabs/puppetlabs-ruby"
        concat:
          ref: "2.2.0"
          repo: "https://github.com/puppetlabs/puppetlabs-concat"
        apt:
          ref: "2.2.2"
          repo: "https://github.com/puppetlabs/puppetlabs-apt"
        portage:
          ref: "2.3.0"
          repo: "https://github.com/gentoo/puppet-portage"
        make:
          ref: "v0.0.5"
          repo: "https://github.com/cmroddy/puppet-make"

    symlinks:
        vision_puppet: '#{source_dir}'
