---
fixtures:
    repositories:
        stdlib:
          ref: "4.12.0"
          repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
        hiera:
          ref: "2.0.1"
          repo: "https://github.com/hunner/hunner-hiera"
        inifile:
          ref: "1.5.0"
          repo: "https://github.com/puppetlabs/puppetlabs-inifile"
        r10k:
          ref: "origin/master"
          repo: "https://github.com/acidprime/r10k"
        puppetdb:
          ref: "5.1.2"
          repo: "http://github.com/puppetlabs/puppetlabs-puppetdb"
        firewall:
          ref: "1.8.1"
          repo: "https://github.com/puppetlabs/puppetlabs-firewall"

    symlinks:
        vision_puppet: '#{source_dir}'
