---
fixtures:
    repositories:
        stdlib:
          ref: "4.24.0"
          repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
        archive:
          ref: "v2.3.0"
          repo: "https://github.com/voxpupuli/puppet-archive"
        inifile:
          ref: "1.5.0"
          repo: "https://github.com/puppetlabs/puppetlabs-inifile"
        vcsrepo:
          ref: "2.2.0"
          repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
        apt:
          ref: "5.0.1"
          repo: "https://github.com/puppetlabs/puppetlabs-apt"
        # PuppetDB for config
        puppetdb:
          ref: "6.0.2"
          repo: "http://github.com/puppetlabs/puppetlabs-puppetdb"

    symlinks:
        vision_puppet: '#{source_dir}'
