---
fixtures:
    repositories:
        stdlib:
          ref: "4.18.0"
          repo: "https://github.com/puppetlabs/puppetlabs-stdlib"

        inifile: # dependency for hiera
          ref: "1.5.0"
          repo: "https://github.com/puppetlabs/puppetlabs-inifile"

        # PuppetDB
        puppetdb:
          ref: "6.0.1"
          repo: "http://github.com/puppetlabs/puppetlabs-puppetdb"
        firewall: # dependency for puppetdb
          ref: "1.8.1"
          repo: "https://github.com/puppetlabs/puppetlabs-firewall"
        postgresql: # dependency for puppetdb
          ref: "5.1.0"
          repo: "https://github.com/puppetlabs/puppetlabs-postgresql"
        concat: # dependency for postgresql
          ref: "2.2.0"
          repo: "https://github.com/puppetlabs/puppetlabs-concat"
        apt: # dependency for postgresql
          ref: "2.2.2"
          repo: "https://github.com/puppetlabs/puppetlabs-apt"

        # r10k
        r10k:
          ref: "v6.1.0"
          repo: "https://github.com/voxpupuli/puppet-r10k"
        gcc: # dependency for r10k
          ref: "0.3.0"
          repo: "https://github.com/puppetlabs/puppetlabs-gcc"
        git: # dependency for r10k
          ref: "0.5.0"
          repo: "https://github.com/puppetlabs/puppetlabs-git"
        vcsrepo: # dependency for r10k
          ref: "2.0.0"
          repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
        ruby: # dependency for r10k
          ref: "1.0.0"
          repo: "https://github.com/puppetlabs/puppetlabs-ruby"
        portage: # dependency for r10k
          ref: "2.3.0"
          repo: "https://github.com/gentoo/puppet-portage"
        make: # dependency for r10k
          ref: "v1.1.0"
          repo: "https://github.com/voxpupuli/puppet-make"

    symlinks:
        vision_puppet: '#{source_dir}'
