HOSTS:
  debian-8-x64:
    docker_container_name: vision_puppet
    default_apply_opts:
      order: random
    platform: debian-8-amd64
    hypervisor : docker
    image: debian:8
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y rsyslog cron locales-all net-tools wget git-core apt-transport-https'
      - 'rm -f /usr/sbin/policy-rc.d'
      - 'useradd puppet'
      - 'mkdir -p /vision/pki/; touch /vision/pki/VisionCA.crt'
CONFIG:
  type: aio

