HOSTS:
  debian-8-x64:
    docker_container_name: mietzekatze
    default_apply_opts:
      order: random
      strict_variables:
    platform: debian-8-amd64
    hypervisor : docker
    image: debian:8
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y cron locales-all net-tools wget'
      - 'rm -f /usr/sbin/policy-rc.d'
CONFIG:
  type: aio

